//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterContactListApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_List
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email_Address { get; set; }
        public string Phone_Number { get; set; }
        public string Title { get; set; }
        public string Contact_Type { get; set; }
        public Nullable<bool> Decision_Maker { get; set; }
        public Nullable<bool> Budget_Holder { get; set; }
        public string Department { get; set; }
        public Nullable<int> Region { get; set; }
        public Nullable<int> VISN { get; set; }
        public string Company { get; set; }
        public string Contract_Coding_Compnay { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string AE { get; set; }
        public Nullable<bool> EPS { get; set; }
        public Nullable<bool> Simulator { get; set; }
        public Nullable<bool> VACC { get; set; }
        public Nullable<bool> VACC_R_Notes { get; set; }
        public Nullable<bool> CDI_Pro { get; set; }
        public Nullable<bool> CDI_Pro_R_Notes { get; set; }
        public Nullable<bool> VERA_Az { get; set; }
        public Nullable<bool> VERA_Az_R_Notes { get; set; }
        public Nullable<bool> OI_T { get; set; }
        public Nullable<bool> NHAC { get; set; }
        public Nullable<bool> Svc_Interrupt_Restore { get; set; }
        public string E_Bulletin { get; set; }
        public Nullable<bool> Webcast_Bulletin { get; set; }
        public Nullable<bool> iSupport_Account { get; set; }
        public Nullable<bool> Bulletin_Reader { get; set; }
        public Nullable<bool> NPS_Fall_2016 { get; set; }
        public Nullable<bool> NPS_Spring_2016 { get; set; }
        public Nullable<bool> NPS_Spring_2015 { get; set; }
        public Nullable<bool> OI_T_Building_Relationships { get; set; }
        public Nullable<bool> Klas { get; set; }
    }
}
